In [ ]:
!pip3 install vision-mamba


: 

In [ ]:
# import torch
import cv2
import numpy as np
from ultralytics import YOLO
from vision_mamba.model import Vim
import torch

model = Vim(
    dim=256,  # Dimension of the model
    heads=8,  # Number of attention heads
    dt_rank=32,  # Rank of the dynamic routing tensor
    dim_inner=256,  # Inner dimension of the model
    d_state=256,  # State dimension of the model
    num_classes=1000,  # Number of output classes
    image_size=224,  # Size of the input image
    patch_size=16,  # Size of the image patch
    channels=3,  # Number of input channels
    dropout=0.1,  # Dropout rate
    depth=12,  # Depth of the model
)


x = torch.randn(1, 3, 244, 244)

# Perform a forward pass through the model
out = model(x)

# Print the shape and output of the forward pass
print(out.shape)
print(out)

# # Read the model
# # open_cv_net = cv2.dnn.readNetFromONNX("./yolov8n.onnx")
# # 1. Video capture with the zeroth camera
# vid_cap = cv2.VideoCapture(0)

# # 2. If the camera does not open, print and exit
# if not vid_cap.isOpened():
#     print("WARNING: ", "camera not opening")
#     exit()



# img =  cv2.imread()
      
# # cv2.imshow("Disp", img)
# # cv2.waitKey(0)


# # get_processed_imgs("./bus.jpg")
# # model()
# # cv2.imshow("Display", img)
# # cv2.waitKey(0)


: 

In [ ]:
def process_img(img):
    # img = input_img.astype(np.float32)
    results = model(img)
    random = np.random.randint
    colors = [ (random(0, 255), random(0, 255), random(0, 255)) for i in range(len(results[0].names)) ] 
    if len(results) > 0:
        for result in results:
            for box in result.boxes.numpy():
                print(box.conf[0])
                print(box.data[0])
                print(box.data[0])
                color = colors[int(box.cls[0])]
                print(color)
                rect_frame = cv2.rectangle(img,
                                        (int(box.data[0][0]),int(box.data[0][1])),
                                        (int(box.data[0][2]),int(box.data[0][3])), 
                                        color=colors[int(box.cls[0])],
                                        thickness=3)
                cv2.putText(rect_frame,
                            "{cls} {conf}".format(cls=results[0].names[box.cls[0]], conf=box.conf[0]),
                            (int(box.data[0][0]),int(box.data[0][1])),
                            fontFace= cv2.FONT_HERSHEY_SIMPLEX,
                            fontScale=1, 
                            color=colors[int(box.cls[0])],
                            thickness=2, 
                            lineType=cv2.LINE_AA)
    return img
    
  

In [ ]:
# 3. Run loop to capture frames for modification/processing
while True:
    # 3a. 
    ret, frame = vid_cap.read()
    if not ret:
        print("WARNING: ", "video not reading correctly")
        break
    img = process_img(frame)
    # color = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    cv2.imshow("Display", img)
    if cv2.waitKey(1) == ord("e"):
        vid_cap.release()
        cv2.destroyAllWindows()
        exit()
    


0: 384x640 2 persons, 97.2ms
Speed: 4.3ms preprocess, 97.2ms inference, 3.5ms postprocess per image at shape (1, 3, 384, 640)
0.77030057
[     0.5668      225.87      320.27      710.69      0.7703           0]
[     0.5668      225.87      320.27      710.69      0.7703           0]
(250, 208, 43)
0.70488787
[     600.71      549.33      813.19      719.02     0.70489           0]
[     600.71      549.33      813.19      719.02     0.70489           0]
(250, 208, 43)

0: 384x640 3 persons, 91.8ms
Speed: 3.7ms preprocess, 91.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
0.71571845
[     600.81      549.65       812.3         719     0.71572           0]
[     600.81      549.65       812.3         719     0.71572           0]
(98, 196, 240)
0.6037459
[    0.84149      205.06      284.19      708.14     0.60375           0]
[    0.84149      205.06      284.19      708.14     0.60375           0]
(98, 196, 240)
0.44203568
[    0.89313      202.58      412.93    